---
- name: Ensure Python 3 is installed
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Python 3 on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: python3
        state: present

    - name: Install Python 3 on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: python3
        state: present
        update_cache: yes

- name: Setup Web Servers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: ec2-user
  tasks:
    - name: Install Apache on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: httpd
        state: present

    - name: Start Apache on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install Apache on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: apache2
        state: present

    - name: Start Apache on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      service:
        name: apache2
        state: started
        enabled: yes

- name: Setup NFS Server
  hosts: nfs
  remote_user: ec2-user
  become: yes
  become_user: ec2-user
  tasks:
    - name: Install NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: nfs-utils
        state: present

    - name: Start NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Export NFS directory on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs *(rw,sync,no_root_squash)"
        create: yes

    - name: Restart NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: nfs-server
        state: restarted

    - name: Install NFS server on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: nfs-kernel-server
        state: present

    - name: Start NFS server on Ubuntu
      when: ans
