---
- name: Ensure Python 3 is installed
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Python 3 on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: python3
        state: present

    - name: Install Python 3 on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: python3
        state: present
        update_cache: yes

- name: Setup Web Servers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install Apache on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: httpd
        state: present

    - name: Start Apache on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install Apache on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: apache2
        state: present

    - name: Start Apache on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      service:
        name: apache2
        state: started
        enabled: yes

- name: Setup NFS Server
  hosts: nfs
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: nfs-utils
        state: present

    - name: Start NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Export NFS directory on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs *(rw,sync,no_root_squash)"
        create: yes

    - name: Restart NFS server on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: nfs-server
        state: restarted

    - name: Install NFS server on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: nfs-kernel-server
        state: present

    - name: Start NFS server on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      service:
        name: nfs-kernel-server
        state: started
        enabled: yes

    - name: Export NFS directory on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      lineinfile:
        path: /etc/exports
        line: "/srv/nfs *(rw,sync,no_root_squash)"
        create: yes

    - name: Restart NFS server on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      service:
        name: nfs-kernel-server
        state: restarted

- name: Setup Database Server
  hosts: db
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install MySQL on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      yum:
        name: mysql-server
        state: present

    - name: Start MySQL on Amazon Linux
      when: ansible_facts['distribution'] == 'Amazon'
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install MySQL on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL on Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'
      service:
        name: mysql
        state: started
        enabled: yes

- name: Setup Load Balancer
  hosts: lb
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Install HAProxy on Ubuntu
      apt:
        name: haproxy
        state: present

    - name: Start HAProxy on Ubuntu
      service:
        name: haproxy
        state: started
        enabled: yes
