---
- name: import common file
  import_playbook: ../static-assignments/common.yml 
  tags: 
    - always 


- name: include env-vars file
  include_playbook: ../dynamic-assignments/env-vars.yml 
  tags: 
    - always 

- name: import databases file
  import_playbook: ../static-assignments/db.yml

- name: import webserver file
  import_playbook: ../static-assignments/webservers.yml

- name: import loadbalancerss assignment
  import_playbook: ../static-assignments/lb.yml
  when: load_balancer_is_required

